[package]
name = "simple-robot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cortex-m = "0.7.7"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7.3"
# rtt-target = { version = "0.4.0", features = ["cortex-m"] }
rtt-target = "0.4.0"
panic-rtt-target ={ version = "0.1.2", features = ["cortex-m"] }
